application: benetag-rhok
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /static
  static_dir: static

- url: /.*
  script: hellobenetag.py
  
- url: /createproduct/.*
  script: create_product.py
  login: required
  
- url: /createfactory/.*
  script: create_factory.py
  login: required  

- url: /createworker/.*
  script: create_worker.py
  login: required
  
- url: /createbadge/.*
  script: create_badge.py
  login: admin